### ISSUE TITLE
Comment model doesn't work by default, and votable_type has unexpected value

### ISSUE THREAD

**Issue by PeterBennink** [jcc/laravel-vote#3]
For some reason a couple of weird things are happening to my installation.

Firstly, the comment model doesn't work, at all. `$comment->voters();` only gives `Illuminate\Database\Eloquent\Relations\MorphToMany`, and every other Comment model command gives `Illuminate\Database\QueryException with message 'SQLSTATE[42S22]: Column not found: 1054 Unknown column 'votes.comment_id' in 'on clause' (SQL: select count(*) as aggregate from 'comments' inner join 'votes' on 'comments'.'id' = 'votes'.'comment_id' where 'votes'.'votable_id' = 3 and 'votes'.'votable_type' = App\Comment)'`. For some reason it's looking for a column in the votes-table with name 'comment_id, but I don't know why.

Secondly, when a comment gets voted, the votable_type value is `App\User`, while it should be `App\Comment`, because otherwise the Comment Model commands just show 0 (I know this because I manually created the correct setup, all Comment Model commands then work as expected.

Thanks in advance!

**Comment by jcc** [comment]
@PeterBennink  Can you tell me how do you use this package？

**Comment by PeterBennink** [comment]
I want to use it as a sort of reddit system. I'm using [this commenting system](https://github.com/actuallymab/laravel-comment), which can also do nested comments. Now I want each comment to be voteable. Thanks for the quick response btw!

**Comment by jcc** [comment]
You can refer to this project [jcc/blog](https://github.com/jcc/blog) that how to user this package.

**Comment by PeterBennink** [comment]
But that's exactly the same information as on github. The problem is that, with that information, I'm still getting the problems defined above.

**Comment by PeterBennink** [comment]
I think the main problem is `Illuminate\Database\QueryException with message 'SQLSTATE[42S22]: Column not found: 1054 Unknown column 'votes.comment_id' in 'on clause' (SQL: select count(*) as aggregate from 'comments' inner join 'votes' on 'comments'.'id' = 'votes'.'comment_id' where 'votes'.'votable_id' = 3 and 'votes'.'votable_type' = App\Comment)'`. It decides that votes should have a `comment_id` column, however, I've searched every file in my Laravel folder, and `comment_id` isn't mentioned anywhere. It just invents a column, randomly.

**Comment by jcc** [comment]
@PeterBennink No, the method you are using is a bit of a problem. Had you add `protected $vote = User::class;` in your comment model?

**Comment by PeterBennink** [comment]
No, should I?

**Comment by jcc** [comment]
@PeterBennink Yes，you try to add `protected $vote = User::class;` in your comment model.

**Comment by PeterBennink** [comment]
This at least solves that error! However, the values things like $comment->countVoters(); gives is still wrong, because the value in votable_type is App\User, and not App\Comment. Would you happen to know how to solve that?

**Comment by jcc** [comment]
@PeterBennink Can you show the error in detail？

**Comment by PeterBennink** [comment]
![screen shot 2017-05-02 at 17 49 57](https://cloud.githubusercontent.com/assets/5647568/25626434/cc3440d8-2f5f-11e7-8813-48485429baec.png)

It should say App\Comment, because that's what I'm voting on, but it says App\User. There isn't really an error I get, the system thinks it's doing the right thing I think. When I type `$comment->countUpVoters();` in `php artisan tinker`, it says 0, even though I _just_ voted that comment.

Edit: when I change App\User to App\Comment manually, the response to `$comment->countUpVoters();` is correct. However, `$comment->voters();` and `$comment->isVotedBy(1);` are still incorrect, showing `Illuminate\Database\Eloquent\Relations\MorphToMany {#722}` and `false`, respectively.

**Comment by jcc** [comment]
@PeterBennink 

You should use up vote as :

```php
$comment = Comment::find(1);

$user->upVote($comment);
```

I think you are not the right way to use it.

**Comment by PeterBennink** [comment]
That's what I thought, but I'm sure I'm using it correctly.

`$user = App\User::find(1);`
`$comment = App\Comment::find(1);`
`$user->upVote($comment);`

**Comment by jcc** [comment]
You refer the file of [https://github.com/jcc/blog/blob/master/app/Http/Controllers/Api/MeController.php](https://github.com/jcc/blog/blob/master/app/Http/Controllers/Api/MeController.php). 

I still think it can work. And I don't konw how you use the package.

Can you show your code of user model and comment model?

**Comment by PeterBennink** [comment]
Sure!

This is laravel/app/User.php
~~~<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Actuallymab\LaravelComment\CanComment;
use Jcc\LaravelVote\Vote;

class User extends Authenticatable
{
    use Notifiable;
    use CanComment;
    use Vote;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}
~~~
And this is laravel/app/Comment.php
~~~
<?php

namespace App;

use Actuallymab\LaravelComment\Models\Comment as BaseComment;
use Actuallymab\LaravelComment\Commentable;
use Cog\Likeable\Contracts\HasLikes as HasLikesContract;
use Cog\Likeable\Traits\HasLikes;
use Jcc\LaravelVote\CanBeVoted;

class Comment extends BaseComment implements HasLikesContract
{
    use Commentable;
	use HasLikes;
	use CanBeVoted;
	
    protected $mustBeApproved = false;
    protected $canBeRated = false;   
    protected $vote = User::class;
    
    public function article()
    {
        return $this->belongsTo('App\Models\Article', 'commentable_id');
    }
}
~~~

**Comment by jcc** [comment]
@PeterBennink OK, I'm very sorry. I find the problem. Thank you very much.

**Comment by jcc** [comment]
@PeterBennink Update your `laravel-vote` code. Thx.

**Comment by PeterBennink** [comment]
Thank you so much! Almost everything is working, however, when I type `$comment->voters();` I still get `Illuminate\Database\Eloquent\Relations\MorphToMany {#719}`.. I'm not completely sure what I should get here, but I'm pretty sure it's not this. If you could fix this I'd be very grateful.

**Comment by jcc** [comment]
@PeterBennink  Oh, You should use it like `$comment->voters` or `$comment->voters()->get()`.

**Comment by PeterBennink** [comment]
That works, thanks!

Edit: I posted another problem, but that was an error in my own code, so I deleted it. Thanks again!

**Comment by PeterBennink** [comment]
For some reason the solution you offered works in `php artisan tinker`, but when I try to implement it in the website, it gives an error.

This is ArticleController.php

~~~
<?php

namespace App\Http\Controllers;

use App\Models\Article;
use App\Comment;
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Auth;

class ArticleController extends Controller
{
    /**
     * Show the profile for the given user.
     *
     * @param  int  $id
     * @return Response
     */
    public function show($id)
    {
        $article = \App\Models\Article::find($id); 
        $author = \App\Models\Article::find($id)->authors()->get(); 
        $category = \App\Models\Article::find($id)->categories()->get(); 
        $username = \App\User::get();
        $user = \Auth::user();
       
        $comment = \App\Comment::find($id);
        $upvotes = $downvotes = 5;
        if($comment->countVoters() > 0){
        	$upvotes = $comment->countUpVoters();
			$downvotes = $comment->countDownVoters();
	    }
       
		if((\Request::get('newComment'))!= null){
			$newComment = \Request::get('newComment');        
			$user->comment($article, $newComment);
        }
		if(\Request::get('upVote')){
			$upvoteID = \Request::get('upVote');
			$upvotedComment = \App\Comment::find($upvoteID);	
			$user->upVote($upvotedComment);
        }
        if((\Request::get('downVote'))){
	        $downvoteID = \Request::get('downVote');
			$downvotedComment = \App\Comment::find($downvoteID);	
			$user->downVote($downvotedComment);
        }  
	     
        return view('singlePaper',compact('article', 'author', 'category','id','comment','user','username','upvotes', 'downvotes'));
    }
~~~
And this is the error:

~~~
FatalErrorException in ArticleController.php line 29:
Call to a member function countVoters() on null
~~~

The other functions (user->comment, user->upVote and user->downVote) work perfectly in this setting.
