### ISSUE TITLE
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'votes.topic_id' in 'on clause'

### ISSUE THREAD

**Issue by ghost** [jcc/laravel-vote#4]
我在Blade模板使用`{{ $topic->countVoters() }}`输出$topic的总vote数，但为什么它会去数据表里面找`topic_id`？我代码里面没写这个，自然也不可能找到。

**Comment by jcc** [comment]
@iVanilla 请问你在 `Topic` 模型里面有没有添加这一行 `protected $vote = User::class;` ? 你尝试加一下，我后面版本会去掉这参数。

**Comment by ghost** [comment]
@jcc 好了，已解决。
